
Vagrant.configure("2") do |config|
  ##### VM definition #####
  config.vm.define "debian" do |config|
  config.vm.hostname = "debian"
  config.vm.box = "debian/testing64"
  config.vm.box_check_update = false
  config.vm.synced_folder "../../debian-playbook", "/debian-playbook"
  config.vm.provision "shell", inline: <<-SHELL
  /bin/bash /debian-playbook/install-prerequisites.sh
  SHELL

  config.vm.provision :ansible do |ansible|
    ansible.limit = "all"
    ansible.playbook = "/home/david/debian-playbook/playbook.yml"
    ansible.verbose = "v"
  end
  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    vb.gui = false
    # Customize the amount of memory on the VM:
    vb.memory = "4096"
    vb.cpus = 4
  end
  end
end