---
dependencies: []

galaxy_info:
  author: tonyapuzzo
  description: Atom Editor for Linux
  company: ""
  license: "license (BSD, MIT)"
  min_ansible_version: 2.0
  platforms:
  - name: EL
    versions:
    - 7
  - name: Debian
    versions:
    - stretch
  - name: Ubuntu
    versions:
    - xenial
  galaxy_tags:
    - editors
