---

# DEB 32-bit: https://go.microsoft.com/fwlink/?LinkID=760680
# DEB 64-bit: https://go.microsoft.com/fwlink/?LinkID=760868
# RPM 32-bit: https://go.microsoft.com/fwlink/?LinkID=760681
# RPM 64-bit: https://go.microsoft.com/fwlink/?LinkID=760867

- name: download and install visual studio code
  apt:
    deb: https://go.microsoft.com/fwlink/?LinkID=760680
  when: ansible_userspace_architecture == 'x86' and (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu')

- name: download and install visual studio code
  apt:
    deb: https://go.microsoft.com/fwlink/?LinkID=760868
  when: ansible_userspace_architecture == 'x86_64' and (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu')


- name: download and install visual studio code
  yum:
    name: https://go.microsoft.com/fwlink/?LinkID=760681
  when: >
    ansible_userspace_architecture == 'x86_64' and
    (ansible_distribution == 'CentOS' or
    ansible_distribution == 'EL' or
    ansible_distribution == 'Fedora' or
    ansible_distribution == 'opensuse' or
    ansible_distribution == 'RedHat' or
    ansible_distribution == 'SLES')

- name: download and install visual studio code
  yum:
    name: https://go.microsoft.com/fwlink/?LinkID=760867
  when: >
    ansible_userspace_architecture == 'x86_64' and
    (ansible_distribution == 'CentOS' or
    ansible_distribution == 'EL' or
    ansible_distribution == 'Fedora' or
    ansible_distribution == 'opensuse' or
    ansible_distribution == 'RedHat' or
    ansible_distribution == 'SLES')