---
  - name: install base packages
    package:
      name: "{{ item }}"
      state: present
    loop:
      - "{{ base_packages }}"

  - name: create fd-find symbolic link
    file:
      src: "/usr/bin/fdfind"
      dest: "/usr/local/bin/fd"
      state: link

